[package]
name = 'luna-rs'
version = '0.1.0'
edition = '2024'

[dependencies]
libc = '0.2.171'
nix = { version = '0.29.0', features = ['mman', 'net', 'socket', 'time', 'uio'] }

[[bin]]
name = 'server'
path = 'src/bin/server.rs'
