name: Rust

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Test command line tool
        run: |
          cargo run -- server >test.tsv &
          server_pid="$!"
          sleep 0.5
          cargo run -- client -e -O count=200 -O usec=30
          kill $server_pid
          wait
          echo "$(wc -l <test.tsv)" -eq 201; echo $?
      - name: Install matplotlib
        run: sudo apt-get install python3-matplotlib
      - name: Create histogram from test output
        run: python3 examples/iat-histogram.py -o png test.tsv
      - uses: actions/upload-artifact@v4
        with:
          name: histogram
          path: |
            test.tsv
            test.png
          if-no-files-found: error
          retention-days: 7

  rust-no-default-features:
    name: Rust (no default features)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --no-default-features --verbose
      - name: Run tests
        run: cargo test --no-default-features --verbose

  python:
    name: Python
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './luna-py'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nox
        uses: wntrblm/nox@2025.10.14
        with:
          python-versions: '3.13'
      - name: Build and test
        run: nox
