name: Rust

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  rust-no-default-features:
    name: Rust (no default features)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --no-default-features --verbose
      - name: Run tests
        run: cargo test --no-default-features --verbose

  python:
    name: Python
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './luna-py'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nox
        uses: wntrblm/nox@2025.02.09
        with:
          python-versions: '3.13'
      - name: Build and test
        run: nox
